# JobBot Prometheus Configuration
# Metrics collection and monitoring for production environment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jobbot-prod'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # JobBot Backend API
  - job_name: 'jobbot-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Nginx Metrics (if nginx-prometheus-exporter is configured)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL Metrics (if postgres_exporter is configured)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Metrics (if redis_exporter is configured)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node/System Metrics (if node_exporter is configured)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Docker Metrics (if cadvisor is configured)
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Celery Metrics (if celery-exporter is configured)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9540']
    metrics_path: /metrics
    scrape_interval: 30s

  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 60s

  # Loki Metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom Business Metrics from JobBot API
  - job_name: 'jobbot-business-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /api/v1/monitoring/metrics
    scrape_interval: 60s
    scrape_timeout: 30s
    params:
      format: ['prometheus']

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500
