"""Add business intelligence tables and models

Revision ID: 0fd8f4a0d773
Revises: a6309067ffbe
Create Date: 2025-05-25 21:29:10.489727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd8f4a0d773'
down_revision = 'a6309067ffbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('size_estimate', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_org', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('instagram_handle', sa.String(length=100), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('discovery_source', sa.String(length=100), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('scrape_frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_scrape_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website_status', sa.String(length=50), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('priority_level', sa.String(length=20), nullable=True),
    sa.Column('contact_attempts', sa.Integer(), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_business_status'), 'companies', ['business_status'], unique=False)
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_discovery_source'), 'companies', ['discovery_source'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_last_scraped'), 'companies', ['last_scraped'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_opportunity_score'), 'companies', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_companies_priority_level'), 'companies', ['priority_level'], unique=False)
    op.create_index(op.f('ix_companies_state'), 'companies', ['state'], unique=False)
    op.create_table('business_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('proposed_solution', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('effort_estimate_hours', sa.Integer(), nullable=True),
    sa.Column('complexity_level', sa.String(length=20), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('pain_point_source', sa.String(length=200), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('demo_description', sa.Text(), nullable=True),
    sa.Column('demo_screenshots', sa.JSON(), nullable=True),
    sa.Column('poc_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('discovery_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_pitch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_business_opportunities_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_opportunities'))
    )
    op.create_index(op.f('ix_business_opportunities_category'), 'business_opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_business_opportunities_company_id'), 'business_opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_opportunities_feasibility_score'), 'business_opportunities', ['feasibility_score'], unique=False)
    op.create_index(op.f('ix_business_opportunities_id'), 'business_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_business_opportunities_opportunity_type'), 'business_opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_business_opportunities_status'), 'business_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_business_opportunities_total_score'), 'business_opportunities', ['total_score'], unique=False)
    op.create_index(op.f('ix_business_opportunities_urgency_score'), 'business_opportunities', ['urgency_score'], unique=False)
    op.create_index(op.f('ix_business_opportunities_value_score'), 'business_opportunities', ['value_score'], unique=False)
    op.create_table('company_tech_stacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=100), nullable=False),
    sa.Column('tech_category', sa.String(length=50), nullable=True),
    sa.Column('tech_version', sa.String(length=50), nullable=True),
    sa.Column('tech_description', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detection_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_outdated', sa.Boolean(), nullable=True),
    sa.Column('is_vulnerable', sa.Boolean(), nullable=True),
    sa.Column('current_version', sa.String(length=50), nullable=True),
    sa.Column('upgrade_available', sa.Boolean(), nullable=True),
    sa.Column('upgrade_priority', sa.String(length=20), nullable=True),
    sa.Column('estimated_effort_hours', sa.Integer(), nullable=True),
    sa.Column('business_impact', sa.String(length=20), nullable=True),
    sa.Column('upgrade_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_tech_stacks_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_tech_stacks'))
    )
    op.create_index(op.f('ix_company_tech_stacks_company_id'), 'company_tech_stacks', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tech_stacks_id'), 'company_tech_stacks', ['id'], unique=False)
    op.create_index(op.f('ix_company_tech_stacks_is_outdated'), 'company_tech_stacks', ['is_outdated'], unique=False)
    op.create_index(op.f('ix_company_tech_stacks_is_vulnerable'), 'company_tech_stacks', ['is_vulnerable'], unique=False)
    op.create_index(op.f('ix_company_tech_stacks_tech_category'), 'company_tech_stacks', ['tech_category'], unique=False)
    op.create_index(op.f('ix_company_tech_stacks_tech_name'), 'company_tech_stacks', ['tech_name'], unique=False)
    op.create_table('decision_makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('personal_website', sa.String(length=500), nullable=True),
    sa.Column('writing_style_analysis', sa.Text(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('pain_points', sa.JSON(), nullable=True),
    sa.Column('influence_level', sa.String(length=20), nullable=True),
    sa.Column('technical_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=50), nullable=True),
    sa.Column('best_contact_time', sa.String(length=50), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('contact_priority', sa.Integer(), nullable=True),
    sa.Column('response_likelihood', sa.Float(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('responses_received', sa.Integer(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_decision_makers_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_makers'))
    )
    op.create_index(op.f('ix_decision_makers_company_id'), 'decision_makers', ['company_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_department'), 'decision_makers', ['department'], unique=False)
    op.create_index(op.f('ix_decision_makers_id'), 'decision_makers', ['id'], unique=False)
    op.create_index(op.f('ix_decision_makers_seniority'), 'decision_makers', ['seniority'], unique=False)
    op.create_index(op.f('ix_decision_makers_title'), 'decision_makers', ['title'], unique=False)
    op.create_table('website_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('audit_type', sa.String(length=50), nullable=True),
    sa.Column('audit_tool', sa.String(length=100), nullable=True),
    sa.Column('page_load_time', sa.Float(), nullable=True),
    sa.Column('first_contentful_paint', sa.Float(), nullable=True),
    sa.Column('largest_contentful_paint', sa.Float(), nullable=True),
    sa.Column('cumulative_layout_shift', sa.Float(), nullable=True),
    sa.Column('time_to_interactive', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=True),
    sa.Column('ssl_grade', sa.String(length=10), nullable=True),
    sa.Column('compression_enabled', sa.Boolean(), nullable=True),
    sa.Column('caching_enabled', sa.Boolean(), nullable=True),
    sa.Column('page_size_bytes', sa.Integer(), nullable=True),
    sa.Column('image_optimization_score', sa.Float(), nullable=True),
    sa.Column('meta_description_present', sa.Boolean(), nullable=True),
    sa.Column('title_tag_optimized', sa.Boolean(), nullable=True),
    sa.Column('security_headers', sa.JSON(), nullable=True),
    sa.Column('security_issues', sa.JSON(), nullable=True),
    sa.Column('vulnerability_count', sa.Integer(), nullable=True),
    sa.Column('improvement_opportunities', sa.JSON(), nullable=True),
    sa.Column('estimated_improvement_impact', sa.Float(), nullable=True),
    sa.Column('priority_fixes', sa.JSON(), nullable=True),
    sa.Column('industry_benchmark_score', sa.Float(), nullable=True),
    sa.Column('improvement_potential_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_website_audits_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_audits'))
    )
    op.create_index(op.f('ix_website_audits_audit_date'), 'website_audits', ['audit_date'], unique=False)
    op.create_index(op.f('ix_website_audits_company_id'), 'website_audits', ['company_id'], unique=False)
    op.create_index(op.f('ix_website_audits_id'), 'website_audits', ['id'], unique=False)
    op.create_table('outreach_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('decision_maker_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('outreach_type', sa.String(length=50), nullable=False),
    sa.Column('subject_line', sa.String(length=500), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('personalization_level', sa.String(length=20), nullable=True),
    sa.Column('personalization_notes', sa.Text(), nullable=True),
    sa.Column('demo_included', sa.Boolean(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('sent_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('response_sentiment', sa.String(length=20), nullable=True),
    sa.Column('requires_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('campaign_name', sa.String(length=200), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('led_to_meeting', sa.Boolean(), nullable=True),
    sa.Column('led_to_project', sa.Boolean(), nullable=True),
    sa.Column('project_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_outreach_records_company_id')),
    sa.ForeignKeyConstraint(['decision_maker_id'], ['decision_makers.id'], name=op.f('fk_outreach_records_decision_maker_id')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['business_opportunities.id'], name=op.f('fk_outreach_records_opportunity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_records'))
    )
    op.create_index(op.f('ix_outreach_records_company_id'), 'outreach_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_decision_maker_id'), 'outreach_records', ['decision_maker_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_id'), 'outreach_records', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_records_opportunity_id'), 'outreach_records', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_outreach_records_outreach_type'), 'outreach_records', ['outreach_type'], unique=False)
    op.create_index(op.f('ix_outreach_records_response_received'), 'outreach_records', ['response_received'], unique=False)
    op.create_index(op.f('ix_outreach_records_sent_date'), 'outreach_records', ['sent_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_records_sent_date'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_response_received'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_outreach_type'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_opportunity_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_decision_maker_id'), table_name='outreach_records')
    op.drop_index(op.f('ix_outreach_records_company_id'), table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_index(op.f('ix_website_audits_id'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_company_id'), table_name='website_audits')
    op.drop_index(op.f('ix_website_audits_audit_date'), table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_index(op.f('ix_decision_makers_title'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_seniority'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_department'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_company_id'), table_name='decision_makers')
    op.drop_table('decision_makers')
    op.drop_index(op.f('ix_company_tech_stacks_tech_name'), table_name='company_tech_stacks')
    op.drop_index(op.f('ix_company_tech_stacks_tech_category'), table_name='company_tech_stacks')
    op.drop_index(op.f('ix_company_tech_stacks_is_vulnerable'), table_name='company_tech_stacks')
    op.drop_index(op.f('ix_company_tech_stacks_is_outdated'), table_name='company_tech_stacks')
    op.drop_index(op.f('ix_company_tech_stacks_id'), table_name='company_tech_stacks')
    op.drop_index(op.f('ix_company_tech_stacks_company_id'), table_name='company_tech_stacks')
    op.drop_table('company_tech_stacks')
    op.drop_index(op.f('ix_business_opportunities_value_score'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_urgency_score'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_total_score'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_status'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_opportunity_type'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_id'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_feasibility_score'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_company_id'), table_name='business_opportunities')
    op.drop_index(op.f('ix_business_opportunities_category'), table_name='business_opportunities')
    op.drop_table('business_opportunities')
    op.drop_index(op.f('ix_companies_state'), table_name='companies')
    op.drop_index(op.f('ix_companies_priority_level'), table_name='companies')
    op.drop_index(op.f('ix_companies_opportunity_score'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_last_scraped'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_companies_discovery_source'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_index(op.f('ix_companies_business_status'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###