"""Initial migration with analytics tables

Revision ID: 37e8630b7bab
Revises: 
Create Date: 2025-05-27 06:42:41.198922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '37e8630b7bab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('is_ab_test', sa.Boolean(), nullable=True),
    sa.Column('variant_a_config', sa.JSON(), nullable=True),
    sa.Column('variant_b_config', sa.JSON(), nullable=True),
    sa.Column('traffic_split', sa.Float(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_opened', sa.Integer(), nullable=True),
    sa.Column('total_clicked', sa.Integer(), nullable=True),
    sa.Column('total_replied', sa.Integer(), nullable=True),
    sa.Column('total_converted', sa.Integer(), nullable=True),
    sa.Column('variant_a_sent', sa.Integer(), nullable=True),
    sa.Column('variant_a_opened', sa.Integer(), nullable=True),
    sa.Column('variant_a_clicked', sa.Integer(), nullable=True),
    sa.Column('variant_a_replied', sa.Integer(), nullable=True),
    sa.Column('variant_a_converted', sa.Integer(), nullable=True),
    sa.Column('variant_b_sent', sa.Integer(), nullable=True),
    sa.Column('variant_b_opened', sa.Integer(), nullable=True),
    sa.Column('variant_b_clicked', sa.Integer(), nullable=True),
    sa.Column('variant_b_replied', sa.Integer(), nullable=True),
    sa.Column('variant_b_converted', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('message_templates', sa.JSON(), nullable=True),
    sa.Column('automation_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advanced_campaigns'))
    )
    op.create_index(op.f('ix_advanced_campaigns_id'), 'advanced_campaigns', ['id'], unique=False)
    op.create_table('analytics_business_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('recurring_revenue', sa.Float(), nullable=True),
    sa.Column('new_revenue', sa.Float(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('qualified_leads', sa.Integer(), nullable=True),
    sa.Column('hot_leads', sa.Integer(), nullable=True),
    sa.Column('converted_leads', sa.Integer(), nullable=True),
    sa.Column('total_opportunities', sa.Integer(), nullable=True),
    sa.Column('pipeline_value', sa.Float(), nullable=True),
    sa.Column('average_deal_size', sa.Float(), nullable=True),
    sa.Column('sales_cycle_days', sa.Float(), nullable=True),
    sa.Column('lead_to_opportunity_rate', sa.Float(), nullable=True),
    sa.Column('opportunity_to_close_rate', sa.Float(), nullable=True),
    sa.Column('overall_conversion_rate', sa.Float(), nullable=True),
    sa.Column('new_customers', sa.Integer(), nullable=True),
    sa.Column('churned_customers', sa.Integer(), nullable=True),
    sa.Column('customer_lifetime_value', sa.Float(), nullable=True),
    sa.Column('customer_acquisition_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_business_metrics'))
    )
    op.create_index(op.f('ix_analytics_business_metrics_id'), 'analytics_business_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_business_metrics_metric_date'), 'analytics_business_metrics', ['metric_date'], unique=False)
    op.create_table('competitive_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('estimated_revenue', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('competitive_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('threats', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('pricing_strategy', sa.Text(), nullable=True),
    sa.Column('key_differentiators', sa.JSON(), nullable=True),
    sa.Column('target_customers', sa.JSON(), nullable=True),
    sa.Column('marketing_channels', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitive_intelligence'))
    )
    op.create_index(op.f('ix_competitive_intelligence_id'), 'competitive_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_competitive_intelligence_industry'), 'competitive_intelligence', ['industry'], unique=False)
    op.create_table('predictive_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('mean_absolute_error', sa.Float(), nullable=True),
    sa.Column('training_data_size', sa.Integer(), nullable=False),
    sa.Column('features_count', sa.Integer(), nullable=False),
    sa.Column('features_list', sa.JSON(), nullable=True),
    sa.Column('training_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictive_models')),
    sa.UniqueConstraint('model_name', name=op.f('uq_predictive_models_model_name'))
    )
    op.create_index(op.f('ix_predictive_models_id'), 'predictive_models', ['id'], unique=False)
    op.create_table('roi_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('investment', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('roi_percentage', sa.Float(), nullable=False),
    sa.Column('leads_generated', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('cost_per_lead', sa.Float(), nullable=True),
    sa.Column('cost_per_acquisition', sa.Float(), nullable=True),
    sa.Column('average_deal_size', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measurement_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('campaign_type', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('channels_used', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roi_metrics'))
    )
    op.create_index(op.f('ix_roi_metrics_campaign_id'), 'roi_metrics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_roi_metrics_id'), 'roi_metrics', ['id'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('company_size_score', sa.Float(), nullable=True),
    sa.Column('industry_fit_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('budget_authority_score', sa.Float(), nullable=True),
    sa.Column('timeline_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('prediction_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_lead_scores_company_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_scores'))
    )
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_index(op.f('ix_lead_scores_score'), 'lead_scores', ['score'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_features', sa.JSON(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('error_percentage', sa.Float(), nullable=True),
    sa.Column('validation_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['predictive_models.id'], name=op.f('fk_model_predictions_model_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_predictions'))
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    op.drop_index('ix_outreach_records_company_id', table_name='outreach_records')
    op.drop_index('ix_outreach_records_decision_maker_id', table_name='outreach_records')
    op.drop_index('ix_outreach_records_id', table_name='outreach_records')
    op.drop_index('ix_outreach_records_opportunity_id', table_name='outreach_records')
    op.drop_index('ix_outreach_records_outreach_type', table_name='outreach_records')
    op.drop_index('ix_outreach_records_response_received', table_name='outreach_records')
    op.drop_index('ix_outreach_records_sent_date', table_name='outreach_records')
    op.drop_table('outreach_records')
    op.drop_index('ix_business_opportunities_category', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_company_id', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_feasibility_score', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_id', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_opportunity_type', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_status', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_total_score', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_urgency_score', table_name='business_opportunities')
    op.drop_index('ix_business_opportunities_value_score', table_name='business_opportunities')
    op.drop_table('business_opportunities')
    op.drop_index('ix_decision_makers_company_id', table_name='decision_makers')
    op.drop_index('ix_decision_makers_department', table_name='decision_makers')
    op.drop_index('ix_decision_makers_id', table_name='decision_makers')
    op.drop_index('ix_decision_makers_seniority', table_name='decision_makers')
    op.drop_index('ix_decision_makers_title', table_name='decision_makers')
    op.drop_table('decision_makers')
    op.drop_index('ix_website_audits_audit_date', table_name='website_audits')
    op.drop_index('ix_website_audits_company_id', table_name='website_audits')
    op.drop_index('ix_website_audits_id', table_name='website_audits')
    op.drop_table('website_audits')
    op.drop_index('ix_company_tech_stacks_company_id', table_name='company_tech_stacks')
    op.drop_index('ix_company_tech_stacks_id', table_name='company_tech_stacks')
    op.drop_index('ix_company_tech_stacks_is_outdated', table_name='company_tech_stacks')
    op.drop_index('ix_company_tech_stacks_is_vulnerable', table_name='company_tech_stacks')
    op.drop_index('ix_company_tech_stacks_tech_category', table_name='company_tech_stacks')
    op.drop_index('ix_company_tech_stacks_tech_name', table_name='company_tech_stacks')
    op.drop_table('company_tech_stacks')
    op.add_column('companies', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('revenue_range', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('founding_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('tech_stack', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('automation_readiness_score', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('digital_maturity_level', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('automation_opportunities', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('pain_points', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('discovery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('last_analyzed', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('analysis_status', sa.String(length=50), nullable=True))
    with op.batch_alter_table('companies') as batch:
        batch.alter_column('domain',
                   existing_type=sa.VARCHAR(length=500),
                   type_=sa.String(length=200),
                   existing_nullable=True)
        batch.alter_column('address',
                   existing_type=sa.VARCHAR(length=500),
                   type_=sa.Text(),
                   existing_nullable=True)
    op.drop_index('ix_companies_business_status', table_name='companies')
    op.drop_index('ix_companies_city', table_name='companies')
    op.drop_index('ix_companies_discovery_source', table_name='companies')
    op.drop_index('ix_companies_last_scraped', table_name='companies')
    op.drop_index('ix_companies_priority_level', table_name='companies')
    op.drop_index('ix_companies_state', table_name='companies')
    op.drop_index('ix_companies_domain', table_name='companies')
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.drop_column('companies', 'response_rate')
    op.drop_column('companies', 'website_url')
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'contact_attempts')
    op.drop_column('companies', 'linkedin_url')
    op.drop_column('companies', 'instagram_handle')
    op.drop_column('companies', 'website_status')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'facebook_url')
    op.drop_column('companies', 'last_contact_date')
    op.drop_column('companies', 'scrape_frequency_days')
    op.drop_column('companies', 'last_scraped')
    op.drop_column('companies', 'github_org')
    op.drop_column('companies', 'size_estimate')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'zip_code')
    op.drop_column('companies', 'business_status')
    op.drop_column('companies', 'twitter_handle')
    op.drop_column('companies', 'next_scrape_date')
    op.drop_column('companies', 'priority_level')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'social_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('social_media', sqlite.JSON(), nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('priority_level', sa.VARCHAR(length=20), nullable=True))
    op.add_column('companies', sa.Column('next_scrape_date', sa.DATETIME(), nullable=True))
    op.add_column('companies', sa.Column('twitter_handle', sa.VARCHAR(length=100), nullable=True))
    op.add_column('companies', sa.Column('business_status', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True))
    op.add_column('companies', sa.Column('city', sa.VARCHAR(length=100), nullable=True))
    op.add_column('companies', sa.Column('size_estimate', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('github_org', sa.VARCHAR(length=200), nullable=True))
    op.add_column('companies', sa.Column('last_scraped', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('companies', sa.Column('scrape_frequency_days', sa.INTEGER(), nullable=True))
    op.add_column('companies', sa.Column('last_contact_date', sa.DATETIME(), nullable=True))
    op.add_column('companies', sa.Column('facebook_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('companies', sa.Column('state', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('website_status', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('instagram_handle', sa.VARCHAR(length=100), nullable=True))
    op.add_column('companies', sa.Column('linkedin_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('companies', sa.Column('contact_attempts', sa.INTEGER(), nullable=True))
    op.add_column('companies', sa.Column('country', sa.VARCHAR(length=50), nullable=True))
    op.add_column('companies', sa.Column('website_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('companies', sa.Column('response_rate', sa.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.create_index('ix_companies_domain', 'companies', ['domain'], unique=1)
    op.create_index('ix_companies_state', 'companies', ['state'], unique=False)
    op.create_index('ix_companies_priority_level', 'companies', ['priority_level'], unique=False)
    op.create_index('ix_companies_last_scraped', 'companies', ['last_scraped'], unique=False)
    op.create_index('ix_companies_discovery_source', 'companies', ['discovery_source'], unique=False)
    op.create_index('ix_companies_city', 'companies', ['city'], unique=False)
    op.create_index('ix_companies_business_status', 'companies', ['business_status'], unique=False)
    op.alter_column('companies', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('companies', 'domain',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('companies', 'analysis_status')
    op.drop_column('companies', 'last_analyzed')
    op.drop_column('companies', 'discovery_date')
    op.drop_column('companies', 'pain_points')
    op.drop_column('companies', 'automation_opportunities')
    op.drop_column('companies', 'digital_maturity_level')
    op.drop_column('companies', 'automation_readiness_score')
    op.drop_column('companies', 'tech_stack')
    op.drop_column('companies', 'founding_year')
    op.drop_column('companies', 'revenue_range')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'website')
    op.create_table('company_tech_stacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('tech_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tech_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tech_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tech_description', sa.TEXT(), nullable=True),
    sa.Column('detection_method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('detection_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_outdated', sa.BOOLEAN(), nullable=True),
    sa.Column('is_vulnerable', sa.BOOLEAN(), nullable=True),
    sa.Column('current_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('upgrade_available', sa.BOOLEAN(), nullable=True),
    sa.Column('upgrade_priority', sa.VARCHAR(length=20), nullable=True),
    sa.Column('estimated_effort_hours', sa.INTEGER(), nullable=True),
    sa.Column('business_impact', sa.VARCHAR(length=20), nullable=True),
    sa.Column('upgrade_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_company_tech_stacks_company_id'),
    sa.PrimaryKeyConstraint('id', name='pk_company_tech_stacks')
    )
    op.create_index('ix_company_tech_stacks_tech_name', 'company_tech_stacks', ['tech_name'], unique=False)
    op.create_index('ix_company_tech_stacks_tech_category', 'company_tech_stacks', ['tech_category'], unique=False)
    op.create_index('ix_company_tech_stacks_is_vulnerable', 'company_tech_stacks', ['is_vulnerable'], unique=False)
    op.create_index('ix_company_tech_stacks_is_outdated', 'company_tech_stacks', ['is_outdated'], unique=False)
    op.create_index('ix_company_tech_stacks_id', 'company_tech_stacks', ['id'], unique=False)
    op.create_index('ix_company_tech_stacks_company_id', 'company_tech_stacks', ['company_id'], unique=False)
    op.create_table('website_audits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('audit_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('audit_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('audit_tool', sa.VARCHAR(length=100), nullable=True),
    sa.Column('page_load_time', sa.FLOAT(), nullable=True),
    sa.Column('first_contentful_paint', sa.FLOAT(), nullable=True),
    sa.Column('largest_contentful_paint', sa.FLOAT(), nullable=True),
    sa.Column('cumulative_layout_shift', sa.FLOAT(), nullable=True),
    sa.Column('time_to_interactive', sa.FLOAT(), nullable=True),
    sa.Column('performance_score', sa.INTEGER(), nullable=True),
    sa.Column('accessibility_score', sa.INTEGER(), nullable=True),
    sa.Column('best_practices_score', sa.INTEGER(), nullable=True),
    sa.Column('seo_score', sa.INTEGER(), nullable=True),
    sa.Column('mobile_friendly', sa.BOOLEAN(), nullable=True),
    sa.Column('ssl_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('ssl_grade', sa.VARCHAR(length=10), nullable=True),
    sa.Column('compression_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('caching_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('page_size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('image_optimization_score', sa.FLOAT(), nullable=True),
    sa.Column('meta_description_present', sa.BOOLEAN(), nullable=True),
    sa.Column('title_tag_optimized', sa.BOOLEAN(), nullable=True),
    sa.Column('security_headers', sqlite.JSON(), nullable=True),
    sa.Column('security_issues', sqlite.JSON(), nullable=True),
    sa.Column('vulnerability_count', sa.INTEGER(), nullable=True),
    sa.Column('improvement_opportunities', sqlite.JSON(), nullable=True),
    sa.Column('estimated_improvement_impact', sa.FLOAT(), nullable=True),
    sa.Column('priority_fixes', sqlite.JSON(), nullable=True),
    sa.Column('industry_benchmark_score', sa.FLOAT(), nullable=True),
    sa.Column('improvement_potential_score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_website_audits_company_id'),
    sa.PrimaryKeyConstraint('id', name='pk_website_audits')
    )
    op.create_index('ix_website_audits_id', 'website_audits', ['id'], unique=False)
    op.create_index('ix_website_audits_company_id', 'website_audits', ['company_id'], unique=False)
    op.create_index('ix_website_audits_audit_date', 'website_audits', ['audit_date'], unique=False)
    op.create_table('decision_makers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('seniority', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('github_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(length=100), nullable=True),
    sa.Column('personal_website', sa.VARCHAR(length=500), nullable=True),
    sa.Column('writing_style_analysis', sa.TEXT(), nullable=True),
    sa.Column('interests', sqlite.JSON(), nullable=True),
    sa.Column('pain_points', sqlite.JSON(), nullable=True),
    sa.Column('influence_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('technical_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('preferred_contact_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('best_contact_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('communication_style', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_priority', sa.INTEGER(), nullable=True),
    sa.Column('response_likelihood', sa.FLOAT(), nullable=True),
    sa.Column('influence_score', sa.FLOAT(), nullable=True),
    sa.Column('last_contacted', sa.DATETIME(), nullable=True),
    sa.Column('total_contacts', sa.INTEGER(), nullable=True),
    sa.Column('responses_received', sa.INTEGER(), nullable=True),
    sa.Column('response_rate', sa.FLOAT(), nullable=True),
    sa.Column('engagement_score', sa.FLOAT(), nullable=True),
    sa.Column('relationship_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_decision_makers_company_id'),
    sa.PrimaryKeyConstraint('id', name='pk_decision_makers')
    )
    op.create_index('ix_decision_makers_title', 'decision_makers', ['title'], unique=False)
    op.create_index('ix_decision_makers_seniority', 'decision_makers', ['seniority'], unique=False)
    op.create_index('ix_decision_makers_id', 'decision_makers', ['id'], unique=False)
    op.create_index('ix_decision_makers_department', 'decision_makers', ['department'], unique=False)
    op.create_index('ix_decision_makers_company_id', 'decision_makers', ['company_id'], unique=False)
    op.create_table('business_opportunities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('opportunity_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('problem_statement', sa.TEXT(), nullable=True),
    sa.Column('proposed_solution', sa.TEXT(), nullable=True),
    sa.Column('estimated_value', sa.FLOAT(), nullable=True),
    sa.Column('estimated_savings', sa.FLOAT(), nullable=True),
    sa.Column('effort_estimate_hours', sa.INTEGER(), nullable=True),
    sa.Column('complexity_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('urgency_score', sa.FLOAT(), nullable=True),
    sa.Column('feasibility_score', sa.FLOAT(), nullable=True),
    sa.Column('value_score', sa.FLOAT(), nullable=True),
    sa.Column('competition_score', sa.FLOAT(), nullable=True),
    sa.Column('total_score', sa.FLOAT(), nullable=True),
    sa.Column('evidence_data', sqlite.JSON(), nullable=True),
    sa.Column('pain_point_source', sa.VARCHAR(length=200), nullable=True),
    sa.Column('validation_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('demo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('demo_description', sa.TEXT(), nullable=True),
    sa.Column('demo_screenshots', sqlite.JSON(), nullable=True),
    sa.Column('poc_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('discovery_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('target_pitch_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_business_opportunities_company_id'),
    sa.PrimaryKeyConstraint('id', name='pk_business_opportunities')
    )
    op.create_index('ix_business_opportunities_value_score', 'business_opportunities', ['value_score'], unique=False)
    op.create_index('ix_business_opportunities_urgency_score', 'business_opportunities', ['urgency_score'], unique=False)
    op.create_index('ix_business_opportunities_total_score', 'business_opportunities', ['total_score'], unique=False)
    op.create_index('ix_business_opportunities_status', 'business_opportunities', ['status'], unique=False)
    op.create_index('ix_business_opportunities_opportunity_type', 'business_opportunities', ['opportunity_type'], unique=False)
    op.create_index('ix_business_opportunities_id', 'business_opportunities', ['id'], unique=False)
    op.create_index('ix_business_opportunities_feasibility_score', 'business_opportunities', ['feasibility_score'], unique=False)
    op.create_index('ix_business_opportunities_company_id', 'business_opportunities', ['company_id'], unique=False)
    op.create_index('ix_business_opportunities_category', 'business_opportunities', ['category'], unique=False)
    op.create_table('outreach_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('decision_maker_id', sa.INTEGER(), nullable=True),
    sa.Column('opportunity_id', sa.INTEGER(), nullable=True),
    sa.Column('outreach_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subject_line', sa.VARCHAR(length=500), nullable=True),
    sa.Column('message_content', sa.TEXT(), nullable=True),
    sa.Column('personalization_level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('personalization_notes', sa.TEXT(), nullable=True),
    sa.Column('demo_included', sa.BOOLEAN(), nullable=True),
    sa.Column('attachment_count', sa.INTEGER(), nullable=True),
    sa.Column('sent_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('response_received', sa.BOOLEAN(), nullable=True),
    sa.Column('response_date', sa.DATETIME(), nullable=True),
    sa.Column('response_content', sa.TEXT(), nullable=True),
    sa.Column('response_sentiment', sa.VARCHAR(length=20), nullable=True),
    sa.Column('requires_followup', sa.BOOLEAN(), nullable=True),
    sa.Column('followup_date', sa.DATETIME(), nullable=True),
    sa.Column('followup_notes', sa.TEXT(), nullable=True),
    sa.Column('campaign_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sequence_number', sa.INTEGER(), nullable=True),
    sa.Column('led_to_meeting', sa.BOOLEAN(), nullable=True),
    sa.Column('led_to_project', sa.BOOLEAN(), nullable=True),
    sa.Column('project_value', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_outreach_records_company_id'),
    sa.ForeignKeyConstraint(['decision_maker_id'], ['decision_makers.id'], name='fk_outreach_records_decision_maker_id'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['business_opportunities.id'], name='fk_outreach_records_opportunity_id'),
    sa.PrimaryKeyConstraint('id', name='pk_outreach_records')
    )
    op.create_index('ix_outreach_records_sent_date', 'outreach_records', ['sent_date'], unique=False)
    op.create_index('ix_outreach_records_response_received', 'outreach_records', ['response_received'], unique=False)
    op.create_index('ix_outreach_records_outreach_type', 'outreach_records', ['outreach_type'], unique=False)
    op.create_index('ix_outreach_records_opportunity_id', 'outreach_records', ['opportunity_id'], unique=False)
    op.create_index('ix_outreach_records_id', 'outreach_records', ['id'], unique=False)
    op.create_index('ix_outreach_records_decision_maker_id', 'outreach_records', ['decision_maker_id'], unique=False)
    op.create_index('ix_outreach_records_company_id', 'outreach_records', ['company_id'], unique=False)
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_lead_scores_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_roi_metrics_id'), table_name='roi_metrics')
    op.drop_index(op.f('ix_roi_metrics_campaign_id'), table_name='roi_metrics')
    op.drop_table('roi_metrics')
    op.drop_index(op.f('ix_predictive_models_id'), table_name='predictive_models')
    op.drop_table('predictive_models')
    op.drop_index(op.f('ix_competitive_intelligence_industry'), table_name='competitive_intelligence')
    op.drop_index(op.f('ix_competitive_intelligence_id'), table_name='competitive_intelligence')
    op.drop_table('competitive_intelligence')
    op.drop_index(op.f('ix_analytics_business_metrics_metric_date'), table_name='analytics_business_metrics')
    op.drop_index(op.f('ix_analytics_business_metrics_id'), table_name='analytics_business_metrics')
    op.drop_table('analytics_business_metrics')
    op.drop_index(op.f('ix_advanced_campaigns_id'), table_name='advanced_campaigns')
    op.drop_table('advanced_campaigns')
    # ### end Alembic commands ###