"""Add business intelligence models for company discovery and opportunity tracking

Revision ID: a6309067ffbe
Revises: 
Create Date: 2025-05-25 21:19:02.069956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6309067ffbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_instances_status'), 'alert_instances', ['status'], unique=False)
    op.create_index(op.f('ix_scrape_sessions_start_time'), 'scrape_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_scrape_sessions_status'), 'scrape_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_session_metrics_metric_name'), 'session_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_session_metrics_timestamp'), 'session_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_site_executions_site_name'), 'site_executions', ['site_name'], unique=False)
    op.create_index(op.f('ix_site_executions_start_time'), 'site_executions', ['start_time'], unique=False)
    op.create_index(op.f('ix_site_executions_status'), 'site_executions', ['status'], unique=False)
    op.create_index(op.f('ix_system_health_timestamp'), 'system_health', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_timestamp'), table_name='system_health')
    op.drop_index(op.f('ix_site_executions_status'), table_name='site_executions')
    op.drop_index(op.f('ix_site_executions_start_time'), table_name='site_executions')
    op.drop_index(op.f('ix_site_executions_site_name'), table_name='site_executions')
    op.drop_index(op.f('ix_session_metrics_timestamp'), table_name='session_metrics')
    op.drop_index(op.f('ix_session_metrics_metric_name'), table_name='session_metrics')
    op.drop_index(op.f('ix_scrape_sessions_status'), table_name='scrape_sessions')
    op.drop_index(op.f('ix_scrape_sessions_start_time'), table_name='scrape_sessions')
    op.drop_index(op.f('ix_alert_instances_status'), table_name='alert_instances')
    # ### end Alembic commands ###